### ISSUE TITLE
About PETS datasets

### ISSUE THREAD

**Issue by mingjieli0111** [jiamingzhang94/Unlearnable-Clusters#4]
Hello, nice work! Could you please share the PETS datasets or how to build it from [Oxford-III_Pet_Dataset](https://www.kaggle.com/datasets/tanlikesmath/the-oxfordiiit-pet-dataset)? Because it seems it doesn't have train split in Kaggle's version.

**Comment by jiamingzhang94** [comment]
Hi,I used the version of https://github.com/Microsoft/robust-models-transfer. But it seems to have been removed by Microsoft. Maybe you can try it on https://github.com/KaiyangZhou/CoOp.
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        11/4/2023 22:32
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [jiamingzhang94/Unlearnable-Clusters] About PETS datasets (Issue #4)
        
      
    
  

Hello, nice work! Could you please share the PETS datasets or how to build it from Oxford-III_Pet_Dataset? Because it seems it doesn't have train split in Kaggle's version.
